#!name=高德地图去广告
#!desc=高德地图去广告
#!author=aijianh

[MITM]
hostname = %APPEND% m5.amap.com, m5-zb.amap.com, oss.amap.com, sns.amap.com

[URL Rewrite]
^https:\/\/.*\.amap\.com\/ws\/banner\/lists\/\? _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/faas\/amap-navigation\/card-service-(car-end|route-plan) _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/shield\/search_poi\/tips_adv\? _ reject-dict
^https:\/\/.*\.amap\.com\/ws\/boss\/order\/car\/king_toolbox_car_bubble _ reject-dict
^https:\/\/.*\.amap\.com\/ws\/boss\/tips\/onscene_visual_optimization _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/faas\/amap-navigation\/main-page-assets _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/faas\/amap-navigation\/main-page-location _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/faas\/amap-navigation\/ridewalk-end-fc _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/shield\/scene\/recommend\? _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/valueadded\/weather\/v2\? _ reject-dict
^https:\/\/.*\.amap\.com\/ws\/msgbox\/pull_mp\? _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/mapapi\/hint_text\/offline_data _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/message\/notice\/list _ reject-dict
^https:\/\/m5\.amap\.com\/ws\/shield\/search\/new_hotword _ reject-dict

[Script]
amap = type=http-response,pattern=^http:\/\/amdc\.m\.taobao\.com\/amdc\/mobileDispatch,requires-body=true,script-path=https://raw.githubusercontent.com/jianh-ai/Quantumult4myself/main/js/ali.js
# 导航净化
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/aos\/perception\/publicTravel\/beforeNavi\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/bus\/plan\/integrate\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/c3frontend\/af-(hotel|launch)\/page\/main\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/perception\/drive\/(routeInfo|routePlan),requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search\/(common\/coupon\/info|poi\/detail),requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search_bff\/hotword\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search_business\/process\/marketingOperationStructured\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search_poi\/(homepage|mps|search\/sp|sug|tips_operation_location),requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
# 首页净化
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/faas\/amap-navigation\/(card-service-plan-home|main-page),requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/frogserver\/aocs\/updatable,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
# 我的净化
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaasv3\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
# 附近页
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search\/nearbyrec_smart\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
# 开屏广告
amap = type=http-response,pattern=^https:\/\/m5\.amap\.com\/ws\/valueadded\/alimama\/splash_screen\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
# 打车净化
amap = type=http-response,pattern=^https:\/\/.*\.amap\.com\/ws\/boss\/(car\/order\/content_info|order_web\/friendly_information),requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/.*\.amap\.com\/ws\/promotion-web\/resource(\/home)?\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
amap = type=http-response,pattern=^https:\/\/.*\.amap\.com\/ws\/sharedtrip\/taxi\/order_detail_car_tips\?,requires-body=true,script-path=https://raw.githubusercontent.com/RuCu6/QuanX/main/Scripts/amap.js
